spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false